cp /usr/local/share/lazarus/components/dbexport/languages/*.po                                    /home/alexs/work/FBManager/languages/dbexport/
cp /usr/local/share/lazarus/components/FBDataSet/languages/*.po                                   /home/alexs/work/FBManager/languages/fbdataset/
cp /usr/local/share/lazarus/components/fpspreadsheet/languages/*.po                               /home/alexs/work/FBManager/languages/fpspreadsheet/
cp /usr/local/share/lazarus/components/lazreport/source/languages/*.po                            /home/alexs/work/FBManager/languages/lazreport/
cp /usr/local/share/lazarus/components/lazreport/source/addons/addfunction/languages/*.po         /home/alexs/work/FBManager/languages/lazreport/
cp /usr/local/share/lazarus/components/lazreport/source/addons/ZeosDB/languages/*.po              /home/alexs/work/FBManager/languages/lazreport/
cp /usr/local/share/lazarus/components/lazreport/source/addons/lrEmailExport/languages/*.po       /home/alexs/work/FBManager/languages/lazreport/
cp /usr/local/share/lazarus/components/lazreport/source/addons/lrspreadsheetexport/languages/*.po /home/alexs/work/FBManager/languages/lazreport/
cp /usr/local/share/lazarus/lcl/languages/*.po                                                    /home/alexs/work/FBManager/languages/lcl/
cp /usr/local/share/lazarus/components/rxnew/languages/*.po                                       /home/alexs/work/FBManager/languages/rx/
